### ISSUE TITLE
Different MTJ implementations

### ISSUE THREAD

**Issue by mikera** [sethyuan/mtj#1]
Hi there!

Looks cool and great to have a core.matrix MTJ implementation! Just stumbled across a different MTJ implementation for Clojure - might be worth you guys joining forces?

https://github.com/madriska/core.matrix.mtj

**Comment by sethyuan** [comment]
Yeah, I found that one too, before I started my own implementation. madriska has only implemented the required protocols, and it has no `seq` friendly wrappers for MTJ. I had to write some Java wrappers for `seq` to work. Also, I wanted a feature rich and efficient MTJ implementation.

**Comment by mikera** [comment]
OK makes sense!

@bradediger just copying you in FYI

**Comment by bradediger** [comment]
Thanks guys, this looks really nice! I was spiking out a rearchitecture of a project I'm working on that currently uses raw Clatrix and JBLAS. I couldn't get the performance within targets in reasonable time so I abandoned the effort.

I've added a note on my repo pointing to @sethyuan's. Cheers!
