### ISSUE TITLE
Change of name? 

### ISSUE THREAD

**Issue by fommil** [sethyuan/mtj#2]
Cool! I'm the maintainer of MTJ and I didn't realise that this was a clojure wrapper :-) maybe you could change the project name to make it more obvious... Matrix Toolkits for Clojure or something. 

Btw, I made a new release last week.

**Comment by mikera** [comment]
Think it would be sensible to rename to avoid confusion. Including for things like Maven coordinates etc. 

@sethyuan - are you still actively maintaining this?

**Comment by sethyuan** [comment]
I'm afraid I no longer have time to maintain this project. Feel free to fork it!
